# Generated by Django 3.2.9 on 2022-11-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_cocoment_cocomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocomment',
            name='content',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=30),
        ),
    ]
