# Generated by Django 3.2.9 on 2022-11-04 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_auto_20221104_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='co_like_users',
            field=models.ManyToManyField(related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
