# Generated by Django 3.2.9 on 2022-11-04 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0005_comment_co_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocomment',
            name='coco_like_users',
            field=models.ManyToManyField(related_name='like_cocomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
